### Post advertising
POST http://localhost:3000/advertising
Content-Type: application/json

{
  "title": "Naushnik",
  "category_id": 1,
  "description": "Quloqqa tiqing, dunyoni unuting",
  "store_name": "Uzum market",
  "start_price": 50000,
  "discount": 15,
  "promo_code": "quloq",
  "url": "https://uzum.uz/ru/product/Bolshie-naushniki-besprovodnye-250869?skuid=376108",
  "img": "https://images.uzum.uz/cfb3a3ivtie1lhbhno4g/original.jpg"
}


### List advertisings
GET http://localhost:3000/advertising


### Show advertising
GET http://localhost:3000/advertising/1



### Edit advertising
PATCH http://localhost:3000/advertising/1
Content-Type: application/json

{
  "start_price": 70000,
  "discount": 90
}


### Delete advertising
DELETE http://localhost:3000/advertising/1
