### Post advertising
POST http://localhost:3000/advertising
Content-Type: application/json

{
  "title": "",
  "category_id": ,
  "description": "",
  "store_name": " ",
  "start_price": ,
  "discount": ,
  "promo_code": "",
  "url": "",
  "img": ""
}


### List advertisings
GET http://localhost:3000/advertising


### Show advertising
GET http://localhost:3000/advertising/:id



### Edit advertising
PATCH http://localhost:3000/advertising/:id
Content-Type: application/json

{
  "title": "",
  "category_id": ,
  "description": "",
  "store_name": " ",
  "start_price": ,
  "discount": ,
  "promo_code": "",
  "url": "",
  "img": ""
}


### Delete advertising
DELETE http://localhost:3000/advertising/:id